version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn start
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: